source:      .
destination: ./public
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     ['Makefile','Dockerfile']
keep_files:  ['.git','.svn']
timezone:    nil

future:      false
show_drafts: false 
limit_posts: 0
highlighter:    true

permalink:     date
paginate_path: 'page:num'

markdown:     kramdown 
markdown_ext:  markdown,mkd,mkdn,md

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
